// Generates a 24s, 120 BPM demo track (mono, 22050 Hz, 16-bit) and writes it
// as a JS file that defines window.DEMO_AUDIO_B64 (so it works from file://).
const fs = require('fs');
const SR = 22050, BPM = 120, BARS = 12;
const beat = 60 / BPM, bar = beat * 4;
const N = Math.round(BARS * bar * SR);
const out = new Float32Array(N);

let seed = 7;
const rand = () => ((seed = (seed * 1664525 + 1013904223) >>> 0) / 4294967296) * 2 - 1;
const mtof = m => 440 * Math.pow(2, (m - 69) / 12);

function add(t0, dur, fn) {
  const s0 = Math.round(t0 * SR), n = Math.round(dur * SR);
  for (let i = 0; i < n && s0 + i < N; i++) out[s0 + i] += fn(i / SR, i);
}
function kick(t) {
  let ph = 0;
  add(t, 0.45, (x) => {
    const f = 45 + 110 * Math.exp(-x * 30);
    ph += (2 * Math.PI * f) / SR;
    return Math.sin(ph) * Math.exp(-x * 7) * 0.9;
  });
}
function clap(t) {
  let lp = 0;
  add(t, 0.25, (x) => {
    const n = rand(); lp += 0.35 * (n - lp);
    const env = Math.exp(-x * 18) * (x < 0.03 ? (Math.floor(x * 300) % 2 ? 1 : 0.4) : 1);
    return (n - lp) * env * 0.45;
  });
}
function hat(t, open) {
  let prev = 0;
  add(t, open ? 0.18 : 0.06, (x) => {
    const n = rand(); const hp = n - prev; prev = n;
    return hp * Math.exp(-x * (open ? 22 : 70)) * 0.18;
  });
}
function bass(t, note, dur) {
  const f = mtof(note); let lp = 0;
  add(t, dur, (x) => {
    const saw = 2 * ((x * f) % 1) - 1;
    lp += 0.08 * (saw - lp);
    const env = Math.min(1, x * 200) * Math.exp(-x * 3);
    return lp * env * 0.7;
  });
}
function pad(t, notes, dur) {
  add(t, dur, (x) => {
    let s = 0;
    for (const m of notes) {
      const f = mtof(m);
      s += Math.sin(2 * Math.PI * f * x) + 0.3 * Math.sin(2 * Math.PI * f * 2.003 * x);
    }
    const env = Math.min(1, x / 0.6) * Math.min(1, (dur - x) / 0.4);
    return (s / notes.length) * env * 0.16;
  });
}
function pluck(t, note) {
  const f = mtof(note);
  add(t, 0.3, (x) => {
    const sq = Math.sin(2 * Math.PI * f * x) > 0 ? 1 : -1;
    return (sq * 0.5 + Math.sin(2 * Math.PI * f * 2 * x) * 0.5) * Math.exp(-x * 14) * 0.12;
  });
}
function riser(t, dur) {
  let prev = 0;
  add(t, dur, (x) => {
    const n = rand(); const hp = n - prev; prev = n;
    return hp * (x / dur) * (x / dur) * 0.25;
  });
}

// Am - F - C - G   (A2 = 45)
const roots = [45, 41, 48, 43];
const chords = [[57, 60, 64], [53, 57, 60], [55, 60, 64], [55, 59, 62]];
const arp = [0, 7, 12, 7, 3, 7, 12, 15];

for (let b = 0; b < BARS; b++) {
  const T = b * bar, ch = b % 4;
  const intro = b < 4, groove = b >= 4 && b < 8, breakdown = b === 8 || b === 9, drop = b >= 10;
  for (let q = 0; q < 4; q++) {
    const t = T + q * beat;
    if (!breakdown) kick(t);
    if ((groove || drop) && (q === 1 || q === 3)) clap(t);
    if (!breakdown) hat(t + beat / 2, q === 3 && b % 2 === 1);
    if (drop || groove) hat(t + beat / 4, false), hat(t + (3 * beat) / 4, false);
    if (groove || drop) bass(t + beat / 2, roots[ch], beat / 2);
  }
  if (!intro) pad(T, chords[ch], bar);
  if (breakdown || drop) for (let i = 0; i < 8; i++) pluck(T + i * (beat / 2), roots[ch] + 24 + arp[i]);
  if (b === 9) riser(T, bar);
}

// normalise + write WAV
let peak = 0; for (const s of out) peak = Math.max(peak, Math.abs(s));
const buf = Buffer.alloc(44 + N * 2);
buf.write('RIFF', 0); buf.writeUInt32LE(36 + N * 2, 4); buf.write('WAVE', 8);
buf.write('fmt ', 12); buf.writeUInt32LE(16, 16); buf.writeUInt16LE(1, 20); buf.writeUInt16LE(1, 22);
buf.writeUInt32LE(SR, 24); buf.writeUInt32LE(SR * 2, 28); buf.writeUInt16LE(2, 32); buf.writeUInt16LE(16, 34);
buf.write('data', 36); buf.writeUInt32LE(N * 2, 40);
for (let i = 0; i < N; i++) buf.writeInt16LE(Math.round((out[i] / peak) * 0.89 * 32767), 44 + i * 2);

const dest = process.argv[2] || '.';
fs.writeFileSync(dest + '/demo-beat.wav', buf);
fs.writeFileSync(dest + '/demo-audio.js',
  '// Demo track: 24s, 120 BPM, generated by code (no copyright). Embedded as base64 so it works offline and from file://.\n' +
  '// Structure: bars 1-4 intro (kick + hats) | 5-8 groove (+ bass, clap, pads) | 9-10 breakdown (no kick, arp + riser) | 11-12 drop.\n' +
  'window.DEMO_AUDIO_B64 = "' + buf.toString('base64') + '";\n');
console.log('samples', N, 'bytes', buf.length);
